language: node_js

notifications:
  email:
    on_success: never

node_js:
  - stable

install:
  - npm install

script:
  - npm run cover

# Send coverage data to Coveralls
after_script: "cat coverage/lcov.info | node_modules/coveralls/bin/coveralls.js"